using FluentAssertions;
using Microsoft.EntityFrameworkCore;
using Npgsql;
using OrchestAI.Domain.Entities;
using OrchestAI.Domain.Enums;
using OrchestAI.Domain.Interfaces;
using OrchestAI.Infrastructure.Data;
using OrchestAI.Infrastructure.Data.Interceptors;
using OrchestAI.Infrastructure.Repositories;
using OrchestAI.Infrastructure.Tenancy;

namespace OrchestAI.Tests.Infrastructure;

// Task 14 audit finding: AgentMemoryRepository.DeleteExpiredAsync and
// AgentMemoryRepository/TaskCheckpointRepository's other ExecuteDeleteAsync call sites were not
// anticipated by the Week 10 plan (which expected zero ExecuteUpdate/ExecuteDelete hits in src/ —
// these two repositories predate Week 10 and were missed by the planning-time grep). EF Core
// versions prior to 7 did NOT apply global query filters to ExecuteDelete/ExecuteUpdate; EF Core 7+
// (this project targets EF Core 8) does apply them automatically, exactly like a normal query,
// unless IgnoreQueryFilters() is called first (which none of these call sites do). This test proves
// that behavior empirically against the real database provider rather than relying on
// documentation alone — DeleteExpiredAsync is the highest-risk of the three ExecuteDelete call
// sites because, unlike DeleteByTaskIdAsync(taskId) and DeleteAsync(id) (which filter on a
// tenant-unique primary/foreign key and so cannot cross tenant boundaries even if the filter were
// somehow bypassed), DeleteExpiredAsync filters only on ExpiresAt — a non-unique column shared
// across all tenants' rows — so it is the one call site where an unfiltered ExecuteDelete could
// actually delete another tenant's data.
//
// Runs against the real local dev Postgres (docker-compose.yml), same as
// TenantBackfillIntegrationTests / CostRollupUniqueIndexIntegrationTests: EF Core's InMemory
// provider cannot translate ExecuteDelete/ExecuteUpdate at all — it throws "could not be
// translated" regardless of filters, a documented InMemory-provider limitation, not evidence
// either way about filter behavior — so a real relational provider is required to prove this. The
// whole test runs inside one transaction that is always rolled back, so the shared dev database is
// left untouched regardless of pass/fail.
public sealed class TenantFilterExecuteDeleteTests
{
    private const string ConnectionString = "Host=localhost;Port=5432;Database=orchestai;Username=orchestai;Password=changeme";

    // Every AppDbContext created for this test must share the SAME physical connection and
    // transaction (via Database.UseTransaction) so that (a) all the fresh-context-per-call
    // repository operations are visible to each other and (b) the whole test can be rolled back as
    // one unit at the end, exactly like the fresh-context-per-repository-call pattern real
    // repositories use via IDbContextFactory, just pinned to one shared transaction for test cleanup.
    private sealed class TransactionScopedDbContextFactory(
        DbContextOptions<AppDbContext> options, NpgsqlTransaction transaction, ICurrentTenantAccessor accessor)
        : IDbContextFactory<AppDbContext>
    {
        public AppDbContext CreateDbContext()
        {
            var ctx = new AppDbContext(options, accessor);
            ctx.Database.UseTransaction(transaction);
            return ctx;
        }

        public Task<AppDbContext> CreateDbContextAsync(CancellationToken cancellationToken = default) =>
            Task.FromResult(CreateDbContext());
    }

    [Fact]
    public async Task DeleteExpiredAsync_ScopedToTenantA_NeverDeletesTenantBsExpiredRows()
    {
        var accessor = new AsyncLocalCurrentTenantAccessor();
        await using var connection = new NpgsqlConnection(ConnectionString);
        await connection.OpenAsync();
        await using var transaction = await connection.BeginTransactionAsync();
        try
        {
            var options = new DbContextOptionsBuilder<AppDbContext>()
                .UseNpgsql(connection)
                .AddInterceptors(new TenantScopingInterceptor(accessor))
                .Options;
            var factory = new TransactionScopedDbContextFactory(options, transaction, accessor);

            var expired = DateTimeOffset.UtcNow.AddMinutes(-5);

            // AgentMemories.TenantId has a FK to Tenants — both tenants need a real row before any
            // tenant-scoped entity can reference them, same as CostRollupUniqueIndexIntegrationTests.
            // Tenant.Id is generated by Tenant.Create (not settable), so the ambient tenant scope
            // below uses the IDs Create assigned rather than pre-generated GUIDs.
            var suffix = Guid.NewGuid().ToString("N");
            var tenantA = Tenant.Create("Tenant A", $"tenant-a-{suffix}");
            var tenantB = Tenant.Create("Tenant B", $"tenant-b-{suffix}");
            var tenantAId = tenantA.Id;
            var tenantBId = tenantB.Id;
            await using (var ctx = await factory.CreateDbContextAsync())
            {
                ctx.Tenants.Add(tenantA);
                ctx.Tenants.Add(tenantB);
                await ctx.SaveChangesAsync();
            }

            Guid tenantAMemoryId, tenantBMemoryId;
            using (accessor.SetTenant(tenantAId))
            {
                await using var ctx = await factory.CreateDbContextAsync();
                var user = TestUserFactory.Create($"execdelete-a-{Guid.NewGuid():N}@test.local");
                var memory = AgentMemory.Create(user.Id, AgentType.Research, "k", "v", expiresAt: expired);
                ctx.Users.Add(user);
                ctx.AgentMemories.Add(memory);
                await ctx.SaveChangesAsync();
                tenantAMemoryId = memory.Id;
            }

            using (accessor.SetTenant(tenantBId))
            {
                await using var ctx = await factory.CreateDbContextAsync();
                var user = TestUserFactory.Create($"execdelete-b-{Guid.NewGuid():N}@test.local");
                var memory = AgentMemory.Create(user.Id, AgentType.Research, "k", "v", expiresAt: expired);
                ctx.Users.Add(user);
                ctx.AgentMemories.Add(memory);
                await ctx.SaveChangesAsync();
                tenantBMemoryId = memory.Id;
            }

            // Act: run the ExecuteDeleteAsync-backed cleanup while scoped to tenant A only.
            using (accessor.SetTenant(tenantAId))
            {
                var repository = new AgentMemoryRepository(factory);
                await repository.DeleteExpiredAsync();
            }

            // Assert, bypassing the ambient scope entirely (IgnoreQueryFilters) to see the raw table
            // state — this is the one legitimate use of IgnoreQueryFilters in a test: verifying what
            // ExecuteDeleteAsync actually did across tenant boundaries, not what a scoped query
            // (which would itself re-apply the filter) reports.
            await using var verifyCtx = await factory.CreateDbContextAsync();
            var remaining = await verifyCtx.AgentMemories
                .IgnoreQueryFilters()
                .Where(m => m.Id == tenantAMemoryId || m.Id == tenantBMemoryId)
                .ToListAsync();

            remaining.Should().ContainSingle(m => m.Id == tenantBMemoryId,
                "tenant B's expired row must survive a delete scoped to tenant A");
            remaining.Should().NotContain(m => m.Id == tenantAMemoryId,
                "tenant A's own expired row should have been removed by the scoped delete");
        }
        finally
        {
            await transaction.RollbackAsync();
        }
    }
}
