// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrchestAI.Infrastructure.Data;

#nullable disable

namespace OrchestAI.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260712162506_AddTenantForeignKeys")]
    partial class AddTenantForeignKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrchestAI.Domain.Entities.AgentExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AgentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<decimal>("CostUsd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,6)")
                        .HasDefaultValue(0m);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("ErrorCategory")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<Guid?>("EvalRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("InputPrompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InputTokens")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("MemoriesInjectedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("OrchestrationTaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("OutputResult")
                        .HasColumnType("text");

                    b.Property<int>("OutputTokens")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("ParentSpanId")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("SpanId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValueSql("substring(replace(gen_random_uuid()::text, '-', ''), 1, 16)");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Pending");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EvalRunId");

                    b.HasIndex("OrchestrationTaskId");

                    b.HasIndex("ParentSpanId");

                    b.HasIndex("SpanId")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.HasIndex("AgentType", "CreatedAt");

                    b.HasIndex("Status", "ErrorCategory");

                    b.ToTable("AgentExecutions", (string)null);
                });

            modelBuilder.Entity("OrchestAI.Domain.Entities.AgentMemory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AgentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamptz");

                    b.Property<int>("Importance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId", "AgentType");

                    b.HasIndex("UserId", "Importance")
                        .IsDescending(false, true);

                    b.HasIndex("UserId", "AgentType", "Key")
                        .IsUnique();

                    b.ToTable("AgentMemories", (string)null);
                });

            modelBuilder.Entity("OrchestAI.Domain.Entities.AgentMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AgentExecutionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AgentExecutionId");

                    b.HasIndex("TenantId");

                    b.ToTable("AgentMessages", (string)null);
                });

            modelBuilder.Entity("OrchestAI.Domain.Entities.AgentRetryAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AgentExecutionId")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("DelayMs")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AgentExecutionId");

                    b.HasIndex("TenantId");

                    b.ToTable("AgentRetryAttempts", (string)null);
                });

            modelBuilder.Entity("OrchestAI.Domain.Entities.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("HashedSecret")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("PublicKeyId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PublicKeyId")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("ApiKeys", null, t =>
                        {
                            t.HasCheckConstraint("CK_ApiKeys_TenantId_NotDefault", "\"TenantId\" <> '00000000-0000-0000-0000-000000000001'");
                        });
                });

            modelBuilder.Entity("OrchestAI.Domain.Entities.CostLedger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AgentExecutionId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CostUsd")
                        .HasColumnType("decimal(10,6)");

                    b.Property<Guid?>("EvalRunId")
                        .HasColumnType("uuid");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OrchestrationTaskId")
                        .HasColumnType("uuid");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Production");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AgentExecutionId");

                    b.HasIndex("EvalRunId");

                    b.HasIndex("Source");

                    b.HasIndex("TenantId");

                    b.HasIndex("OrchestrationTaskId", "RecordedAt")
                        .IsDescending(false, true);

                    b.ToTable("CostLedger", (string)null);
                });

            modelBuilder.Entity("OrchestAI.Domain.Entities.CostRollup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AgentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("CostUsd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,6)")
                        .HasDefaultValue(0m);

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("ExecutionCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("InputTokens")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("OutputTokens")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId", "Date");

                    b.HasIndex("Date", "UserId", "AgentType", "Model")
                        .IsUnique();

                    b.ToTable("CostRollups", (string)null);
                });

            modelBuilder.Entity("OrchestAI.Domain.Entities.EvalCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("ExpectedCriteria")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("InputPayload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<decimal>("RegressionThreshold")
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("ScorerType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("SuiteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SuiteId");

                    b.HasIndex("TenantId");

                    b.ToTable("EvalCases", (string)null);
                });

            modelBuilder.Entity("OrchestAI.Domain.Entities.EvalResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AgentExecutionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EvalCaseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EvalRunId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean");

                    b.Property<string>("Rubric")
                        .HasColumnType("text");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(5,4)");

                    b.Property<DateTimeOffset>("ScoredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("ScorerOutput")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ScorerType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ScorerVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AgentExecutionId");

                    b.HasIndex("EvalCaseId");

                    b.HasIndex("TenantId");

                    b.HasIndex("EvalRunId", "EvalCaseId")
                        .IsUnique();

                    b.HasIndex("AgentExecutionId", "ScorerType", "ScorerVersion")
                        .IsUnique()
                        .HasFilter("\"EvalCaseId\" IS NULL AND \"AgentExecutionId\" IS NOT NULL");

                    b.ToTable("EvalResults", (string)null);
                });

            modelBuilder.Entity("OrchestAI.Domain.Entities.EvalRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("BaselineRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<bool>("ForceRescore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Rubric")
                        .HasColumnType("text");

                    b.Property<string>("SelectionCriteriaJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("SkippedAlreadyScoredCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("LiveSuite");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("SubjectVersion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("SuiteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("TriggeredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("BaselineRunId");

                    b.HasIndex("Source");

                    b.HasIndex("Status");

                    b.HasIndex("SuiteId");

                    b.HasIndex("TenantId");

                    b.ToTable("EvalRuns", (string)null);
                });

            modelBuilder.Entity("OrchestAI.Domain.Entities.EvalSuite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TargetAgentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TargetAgentType");

                    b.HasIndex("TenantId");

                    b.ToTable("EvalSuites", (string)null);
                });

            modelBuilder.Entity("OrchestAI.Domain.Entities.McpToolCall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AgentExecutionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorCategory")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("InputParameters")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string>("OutputResult")
                        .HasColumnType("text");

                    b.Property<string>("ParentSpanId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValueSql("substring(replace(gen_random_uuid()::text, '-', ''), 1, 16)");

                    b.Property<string>("SpanId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValueSql("substring(replace(gen_random_uuid()::text, '-', ''), 1, 16)");

                    b.Property<bool>("Success")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AgentExecutionId");

                    b.HasIndex("ParentSpanId");

                    b.HasIndex("SpanId")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.HasIndex("Success", "ErrorCategory");

                    b.ToTable("McpToolCalls", (string)null);
                });

            modelBuilder.Entity("OrchestAI.Domain.Entities.ModelPricing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("InputPerMillion")
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("OutputPerMillion")
                        .HasColumnType("decimal(10,4)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("Model")
                        .IsUnique();

                    b.ToTable("ModelPricing", (string)null);
                });

            modelBuilder.Entity("OrchestAI.Domain.Entities.OrchestrationTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ApprovalNote")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ApprovalRequestedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("ApprovalStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("FinalResult")
                        .HasColumnType("text");

                    b.Property<bool>("RequireApproval")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("ResumedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Pending");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("TotalCostUsd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,6)")
                        .HasDefaultValue(0m);

                    b.Property<int>("TotalInputTokens")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalOutputTokens")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValueSql("replace(gen_random_uuid()::text, '-', '')");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserPrompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("TenantId");

                    b.HasIndex("TraceId")
                        .IsUnique();

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true);

                    b.ToTable("OrchestrationTasks", (string)null);
                });

            modelBuilder.Entity("OrchestAI.Domain.Entities.TaskCheckpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AgentExecutionId")
                        .HasColumnType("uuid");

                    b.Property<string>("AgentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CheckpointedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal>("CostUsd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,6)")
                        .HasDefaultValue(0m);

                    b.Property<int>("InputTokens")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("OrchestrationTaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("Output")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OutputTokens")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("OrchestrationTaskId", "AgentType")
                        .IsUnique();

                    b.ToTable("TaskCheckpoints", (string)null);
                });

            modelBuilder.Entity("OrchestAI.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Active");

                    b.Property<DateTimeOffset?>("SuspendedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tenants", (string)null);
                });

            modelBuilder.Entity("OrchestAI.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("OrchestAI.Domain.Entities.AgentExecution", b =>
                {
                    b.HasOne("OrchestAI.Domain.Entities.OrchestrationTask", "OrchestrationTask")
                        .WithMany("AgentExecutions")
                        .HasForeignKey("OrchestrationTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrchestAI.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrchestrationTask");
                });

            modelBuilder.Entity("OrchestAI.Domain.Entities.AgentMemory", b =>
                {
                    b.HasOne("OrchestAI.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrchestAI.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrchestAI.Domain.Entities.AgentMessage", b =>
                {
                    b.HasOne("OrchestAI.Domain.Entities.AgentExecution", "AgentExecution")
                        .WithMany("Messages")
                        .HasForeignKey("AgentExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrchestAI.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AgentExecution");
                });

            modelBuilder.Entity("OrchestAI.Domain.Entities.AgentRetryAttempt", b =>
                {
                    b.HasOne("OrchestAI.Domain.Entities.AgentExecution", "AgentExecution")
                        .WithMany()
                        .HasForeignKey("AgentExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrchestAI.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AgentExecution");
                });

            modelBuilder.Entity("OrchestAI.Domain.Entities.ApiKey", b =>
                {
                    b.HasOne("OrchestAI.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("OrchestAI.Domain.Entities.CostLedger", b =>
                {
                    b.HasOne("OrchestAI.Domain.Entities.AgentExecution", "AgentExecution")
                        .WithMany()
                        .HasForeignKey("AgentExecutionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OrchestAI.Domain.Entities.OrchestrationTask", "OrchestrationTask")
                        .WithMany()
                        .HasForeignKey("OrchestrationTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrchestAI.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AgentExecution");

                    b.Navigation("OrchestrationTask");
                });

            modelBuilder.Entity("OrchestAI.Domain.Entities.CostRollup", b =>
                {
                    b.HasOne("OrchestAI.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OrchestAI.Domain.Entities.EvalCase", b =>
                {
                    b.HasOne("OrchestAI.Domain.Entities.EvalSuite", "Suite")
                        .WithMany("Cases")
                        .HasForeignKey("SuiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrchestAI.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Suite");
                });

            modelBuilder.Entity("OrchestAI.Domain.Entities.EvalResult", b =>
                {
                    b.HasOne("OrchestAI.Domain.Entities.EvalCase", "Case")
                        .WithMany()
                        .HasForeignKey("EvalCaseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OrchestAI.Domain.Entities.EvalRun", "Run")
                        .WithMany()
                        .HasForeignKey("EvalRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrchestAI.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("Run");
                });

            modelBuilder.Entity("OrchestAI.Domain.Entities.EvalRun", b =>
                {
                    b.HasOne("OrchestAI.Domain.Entities.EvalRun", "BaselineRun")
                        .WithMany()
                        .HasForeignKey("BaselineRunId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OrchestAI.Domain.Entities.EvalSuite", "Suite")
                        .WithMany()
                        .HasForeignKey("SuiteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OrchestAI.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BaselineRun");

                    b.Navigation("Suite");
                });

            modelBuilder.Entity("OrchestAI.Domain.Entities.EvalSuite", b =>
                {
                    b.HasOne("OrchestAI.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OrchestAI.Domain.Entities.McpToolCall", b =>
                {
                    b.HasOne("OrchestAI.Domain.Entities.AgentExecution", "AgentExecution")
                        .WithMany("ToolCalls")
                        .HasForeignKey("AgentExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrchestAI.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AgentExecution");
                });

            modelBuilder.Entity("OrchestAI.Domain.Entities.OrchestrationTask", b =>
                {
                    b.HasOne("OrchestAI.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrchestAI.Domain.Entities.User", "User")
                        .WithMany("Tasks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrchestAI.Domain.Entities.TaskCheckpoint", b =>
                {
                    b.HasOne("OrchestAI.Domain.Entities.OrchestrationTask", "OrchestrationTask")
                        .WithMany()
                        .HasForeignKey("OrchestrationTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrchestAI.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrchestrationTask");
                });

            modelBuilder.Entity("OrchestAI.Domain.Entities.AgentExecution", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("ToolCalls");
                });

            modelBuilder.Entity("OrchestAI.Domain.Entities.EvalSuite", b =>
                {
                    b.Navigation("Cases");
                });

            modelBuilder.Entity("OrchestAI.Domain.Entities.OrchestrationTask", b =>
                {
                    b.Navigation("AgentExecutions");
                });

            modelBuilder.Entity("OrchestAI.Domain.Entities.User", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
